[package]
name = "acu-patches"
version = "0.5.0"
authors = ["lnx00"]
edition = "2024"

[features]
default = []
plugin = ["dep:assert-offset", "dep:tracing-subscriber"]

[lib]
crate-type = ["cdylib"]

[dependencies]
framework = { path = "../framework" }
tracing = { workspace = true }
enable-ansi-support = { workspace = true }
toml = { workspace = true }
serde = { workspace = true }
libmem = { workspace = true }
windows = { workspace = true }

# Plugin-only dependencies
assert-offset = { version = "0.1.1", optional = true }
tracing-subscriber = { workspace = true, optional = true }
