[workspace]
resolver = "3"
members = [
    # x86_64
    "x64/acu-patches/core",
    "x64/acu-patches/standalone",
    "x64/acu-patches/plugin",
    "x64/acs-patches",
    "x64/mesom-patches",
    "x64/mesow-patches",
    "x64/wd-patches",
    "x64/lswtss-patches",

    # x86
    "x86/fc3-patches",
    "x86/fc3bd-patches",
    "x86/sodyose-patches",

    # Shared
    "framework",
]
default-members = ["framework"]

[workspace.dependencies]
assert-offset = "0.1.2"
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
tracing-appender = "0.2"
enable-ansi-support = "0.3"
toml = "1"
serde = { version = "1.0", features = ["derive"] }
libmem = "5"
winres = "0.1"
windows = { version = "0.62", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_System_SystemServices",
    "Win32_System_Console",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_System_LibraryLoader",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_SystemInformation",
    "Win32_System_Memory",
    "Wdk_System_Threading",
] }

[profile.release]
lto = true
