show_console = false # Attach debug console on startup
allow_unloading = false # Allow unloading of patches at runtime
suppress_version_mismatch = false # Suppress version mismatch warnings on startup

[patches]
disable_camera_smoothing = true